Document: sdlcave
Title: Debian sdlcave Manual
Author: <insert document author here>
Abstract: This manual describes what sdlcave is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/sdlcave/sdlcave.sgml.gz

Format: postscript
Files: /usr/share/doc/sdlcave/sdlcave.ps.gz

Format: text
Files: /usr/share/doc/sdlcave/sdlcave.text.gz

Format: HTML
Index: /usr/share/doc/sdlcave/html/index.html
Files: /usr/share/doc/sdlcave/html/*.html

  
